import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Cart from '../components/index'
import {
  ApolloClient,
  InMemoryCache,
  ApolloProvider,
  gql,
} from '@apollo/client'

const inter = Inter({ subsets: ['latin'] })

const client = new ApolloClient({
  uri: 'https://flyby-router-demo.herokuapp.com/',
  cache: new InMemoryCache(),
})

export default function Home() {
  return (
    <>
      <Head>
        <title>Poke GraphQL</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="ContainerTitle">
          <img
            className="PokeLogo"
            src="https://pokemon-web-app.web.app/static/media/logo.4e120cee.svg"
            alt="Logo"
          />
        </div>
        <div className="App">
          <Cart />
          
        </div>
      </main>
    </>
  )
}
