import Head from 'next/head'
import Card from '../components/Card/index'
import InfoScreen from '@/components/InfoScreen'
import { ApolloClient, InMemoryCache, ApolloProvider } from '@apollo/client'



export default function Home() {

  const client = new ApolloClient({
    uri: 'https://graphql-pokeapi.graphcdn.app/',
    cache: new InMemoryCache(),
  })

  return (
    <>
      <Head>
        <title>Poke GraphQL</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="ContainerTitle" >
          <img
            className="PokeLogo"
            src="https://pokemon-web-app.web.app/static/media/logo.4e120cee.svg"
            alt="Logo"
          />
        </div>

        <div className="App">
          <ApolloProvider client={client}>
            <InfoScreen />
          </ApolloProvider> 
          {/* <ApolloProvider client={client}>
            <Card />
          </ApolloProvider> */}
        </div>

        {/* Pantalla info de pokemon  */}
        <div></div>
      </main>
    </>
  )
}


